name: test.yml
on: pull_request

jobs:
  test:
    name: Python Unit test for basewebapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Run Tests
        run: python -m poetry run python -m unittest discover -s test/
